services:
  - type: web
    name: glamstore
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn glamstore.wsgi:application --bind 0.0.0.0:8000
    postDeployCommand: bash post_deploy.sh
    envVars:
      - key: DATABASE_URL
        scope: build
      - key: PYTHON_VERSION
        value: 3.13.0
