services:
  - type: web
    name: glamstore
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn glamstore.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PYTHONUNBUFFERED
        value: true

  - type: cron
    name: enviar-correos-pendientes
    schedule: "*/5 * * * *"
    command: "python manage.py enviar_correos_pendientes"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
